services:
  demo-app:
    image: automaticbytes/demo-app
    ports:
      - "3100:3100"

  tests:
    image: mcr.microsoft.com/playwright:v1.54.1-jammy
    working_dir: /work
    volumes:
      - ./:/work
      - ./playwright-report:/work/playwright-report
    depends_on:
      - demo-app
    ports:
      - "9323:9323" # to access playwright report in browser
    environment:
      BASE_URL: "http://demo-app:3100"
    command: >
      bash -ce "
        echo 'Waiting for demo-app...';
        until curl -s --head --fail http://demo-app:3100 > /dev/null; do
          sleep 1;
        done;
        echo 'demo-app is ready!';
        npm install;
        npx playwright install --with-deps;
        npx playwright test --reporter=line"
